In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df1 = pd.read_csv('drive/My Drive/Data ISPU Jakarta 2021/ISPU Jakarta Januari 2021.csv')
df2 = pd.read_csv('drive/My Drive/Data ISPU Jakarta 2021/ISPU Jakarta Februari 2021.csv')
df3 = pd.read_csv('drive/My Drive/Data ISPU Jakarta 2021/ISPU Jakarta Maret 2021.csv')
df4 = pd.read_csv('drive/My Drive/Data ISPU Jakarta 2021/ISPU Jakarta April 2021.csv')
df5 = pd.read_csv('drive/My Drive/Data ISPU Jakarta 2021/ISPU Jakarta Mei 2021.csv')
df6 = pd.read_csv('drive/My Drive/Data ISPU Jakarta 2021/ISPU Jakarta Juni 2021.csv')
df7 = pd.read_csv('drive/My Drive/Data ISPU Jakarta 2021/ISPU Jakarta Juli 2021.csv')
df8 = pd.read_csv('drive/My Drive/Data ISPU Jakarta 2021/ISPU Jakarta Agustus 2021.csv')
df9 = pd.read_csv('drive/My Drive/Data ISPU Jakarta 2021/ISPU Jakarta September 2021.csv')
df10 = pd.read_csv('drive/My Drive/Data ISPU Jakarta 2021/ISPU Jakarta Oktober 2021.csv')
df11 = pd.read_csv('drive/My Drive/Data ISPU Jakarta 2021/ISPU Jakarta November 2021.csv')
df12 = pd.read_csv('drive/My Drive/Data ISPU Jakarta 2021/ISPU Jakarta Desember 2021.csv')

In [ ]:
# Cek panjang data

print(df1.shape)
print(df2.shape)
print(df3.shape)
print(df4.shape)
print(df5.shape)
print(df6.shape)
print(df7.shape)
print(df8.shape)
print(df9.shape)
print(df10.shape)
print(df11.shape)
print(df12.shape)

(155, 11)
(140, 11)
(155, 11)
(150, 11)
(155, 11)
(150, 11)
(155, 11)
(155, 11)
(150, 11)
(155, 11)
(150, 11)
(155, 11)

In [ ]:
df1

,tanggal,stasiun,pm10,pm25,so2,co,o3,no2,max,critical,categori
0,2021-01-01,DKI1 (Bunderan HI),38,53,29,6,31,13,53,PM25,SEDANG
1,2021-01-02,DKI1 (Bunderan HI),27,46,27,7,47,7,47,O3,BAIK
2,2021-01-03,DKI1 (Bunderan HI),44,58,25,7,40,13,58,PM25,SEDANG
3,2021-01-04,DKI1 (Bunderan HI),30,48,24,4,32,7,48,PM25,BAIK
4,2021-01-05,DKI1 (Bunderan HI),38,53,24,6,31,9,53,PM25,SEDANG
...,...,...,...,...,...,...,...,...,...,...,...
150,2021-01-27,DKI5 (Kebon Jeruk) Jakarta Barat,15,NaN,16,5,20,---,20,CO,BAIK
151,2021-01-28,DKI5 (Kebon Jeruk) Jakarta Barat,28,NaN,19,11,28,---,28,PM10,BAIK
152,2021-01-29,DKI5 (Kebon Jeruk) Jakarta Barat,30,NaN,22,10,32,11,32,CO,BAIK
153,2021-01-30,DKI5 (Kebon Jeruk) Jakarta Barat,24,NaN,17,8,27,10,27,CO,BAIK
154,2021-01-31,DKI5 (Kebon Jeruk) Jakarta Barat,41,NaN,17,19,29,8,41,PM10,BAIK

In [ ]:
# Gabungkan data

df_2021 = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12]).reset_index().drop(columns=['index'])
df_2021

,tanggal,stasiun,pm10,pm25,so2,co,o3,no2,max,critical,categori
0,2021-01-01,DKI1 (Bunderan HI),38,53,29,6,31,13,53,PM25,SEDANG
1,2021-01-02,DKI1 (Bunderan HI),27,46,27,7,47,7,47,O3,BAIK
2,2021-01-03,DKI1 (Bunderan HI),44,58,25,7,40,13,58,PM25,SEDANG
3,2021-01-04,DKI1 (Bunderan HI),30,48,24,4,32,7,48,PM25,BAIK
4,2021-01-05,DKI1 (Bunderan HI),38,53,24,6,31,9,53,PM25,SEDANG
...,...,...,...,...,...,...,...,...,...,...,...
1820,2021-12-27,DKI5 (Kebon Jeruk) Jakarta Barat,54,76,36,14,21,47,76,PM25,SEDANG
1821,2021-12-28,DKI5 (Kebon Jeruk) Jakarta Barat,44,68,20,11,21,33,68,PM25,SEDANG
1822,2021-12-29,DKI5 (Kebon Jeruk) Jakarta Barat,34,54,28,8,25,29,54,PM25,SEDANG
1823,2021-12-30,DKI5 (Kebon Jeruk) Jakarta Barat,53,75,25,15,23,44,75,PM25,SEDANG
1824,2021-12-31,DKI5 (Kebon Jeruk) Jakarta Barat,60,87,28,19,30,53,87,PM25,SEDANG

In [ ]:
df_2021.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   tanggal   1825 non-null   object
 1   stasiun   1825 non-null   object
 2   pm10      1825 non-null   object
 3   pm25      1763 non-null   object
 4   so2       1825 non-null   object
 5   co        1825 non-null   object
 6   o3        1825 non-null   object
 7   no2       1825 non-null   object
 8   max       1825 non-null   object
 9   critical  1809 non-null   object
 10  categori  1824 non-null   object
dtypes: object(11)
memory usage: 157.0+ KB

In [ ]:
# Cek missing value

df_2021.isnull().sum()

tanggal      0
stasiun      0
pm10         0
pm25        62
so2          0
co           0
o3           0
no2          0
max          0
critical    16
categori     1
dtype: int64

In [ ]:
# Cek kelas data kategori

df_2021.categori.unique()

array(['SEDANG', 'BAIK', 'TIDAK SEHAT', 'TIDAK ADA DATA', nan],
      dtype=object)

In [ ]:
df_2021_new = df_ISPU2021.copy()

In [ ]:
# Replace string to NaN

for kolom in df_2021_new.drop(columns=['tanggal','stasiun','critical']).columns:
  df_2021_new[kolom] = df_2021_new[kolom].replace(r'---',np.NaN,regex=True)

df_2021_new

,tanggal,stasiun,pm10,pm25,so2,co,o3,no2,max,critical,categori
0,2021-01-01,DKI1 (Bunderan HI),38,53,29,6,31,13,53,PM25,SEDANG
1,2021-01-02,DKI1 (Bunderan HI),27,46,27,7,47,7,47,O3,BAIK
2,2021-01-03,DKI1 (Bunderan HI),44,58,25,7,40,13,58,PM25,SEDANG
3,2021-01-04,DKI1 (Bunderan HI),30,48,24,4,32,7,48,PM25,BAIK
4,2021-01-05,DKI1 (Bunderan HI),38,53,24,6,31,9,53,PM25,SEDANG
...,...,...,...,...,...,...,...,...,...,...,...
1820,2021-12-27,DKI5 (Kebon Jeruk) Jakarta Barat,54,76,36,14,21,47,76,PM25,SEDANG
1821,2021-12-28,DKI5 (Kebon Jeruk) Jakarta Barat,44,68,20,11,21,33,68,PM25,SEDANG
1822,2021-12-29,DKI5 (Kebon Jeruk) Jakarta Barat,34,54,28,8,25,29,54,PM25,SEDANG
1823,2021-12-30,DKI5 (Kebon Jeruk) Jakarta Barat,53,75,25,15,23,44,75,PM25,SEDANG
1824,2021-12-31,DKI5 (Kebon Jeruk) Jakarta Barat,60,87,28,19,30,53,87,PM25,SEDANG

In [ ]:
df_2021_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   tanggal   1825 non-null   object
 1   stasiun   1825 non-null   object
 2   pm10      1757 non-null   object
 3   pm25      1725 non-null   object
 4   so2       1711 non-null   object
 5   co        1789 non-null   object
 6   o3        1757 non-null   object
 7   no2       1790 non-null   object
 8   max       1825 non-null   object
 9   critical  1809 non-null   object
 10  categori  1824 non-null   object
dtypes: object(11)
memory usage: 157.0+ KB

In [ ]:
df_2021_new.isna().sum()

tanggal       0
stasiun       0
pm10         68
pm25        100
so2         114
co           36
o3           68
no2          35
max           0
critical     16
categori      1
dtype: int64

In [ ]:
# Drop data mengandung NaN

df_2021_new = df_2021_new.dropna(axis=0)
df_2021_new.isnull().sum()

tanggal     0
stasiun     0
pm10        0
pm25        0
so2         0
co          0
o3          0
no2         0
max         0
critical    0
categori    0
dtype: int64

In [ ]:
# Data bersih

df_2021_new.shape

(1517, 11)

In [ ]:
df_2021_new.categori.value_counts()

SEDANG         1147
TIDAK SEHAT     245
BAIK            125
Name: categori, dtype: int64

In [ ]:
df_2021_new

,tanggal,stasiun,pm10,pm25,so2,co,o3,no2,max,critical,categori
0,2021-01-01,DKI1 (Bunderan HI),38,53,29,6,31,13,53,PM25,SEDANG
1,2021-01-02,DKI1 (Bunderan HI),27,46,27,7,47,7,47,O3,BAIK
2,2021-01-03,DKI1 (Bunderan HI),44,58,25,7,40,13,58,PM25,SEDANG
3,2021-01-04,DKI1 (Bunderan HI),30,48,24,4,32,7,48,PM25,BAIK
4,2021-01-05,DKI1 (Bunderan HI),38,53,24,6,31,9,53,PM25,SEDANG
...,...,...,...,...,...,...,...,...,...,...,...
1820,2021-12-27,DKI5 (Kebon Jeruk) Jakarta Barat,54,76,36,14,21,47,76,PM25,SEDANG
1821,2021-12-28,DKI5 (Kebon Jeruk) Jakarta Barat,44,68,20,11,21,33,68,PM25,SEDANG
1822,2021-12-29,DKI5 (Kebon Jeruk) Jakarta Barat,34,54,28,8,25,29,54,PM25,SEDANG
1823,2021-12-30,DKI5 (Kebon Jeruk) Jakarta Barat,53,75,25,15,23,44,75,PM25,SEDANG
1824,2021-12-31,DKI5 (Kebon Jeruk) Jakarta Barat,60,87,28,19,30,53,87,PM25,SEDANG

In [ ]:
df_2021_new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1517 entries, 0 to 1824
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   tanggal   1517 non-null   object
 1   stasiun   1517 non-null   object
 2   pm10      1517 non-null   object
 3   pm25      1517 non-null   object
 4   so2       1517 non-null   object
 5   co        1517 non-null   object
 6   o3        1517 non-null   object
 7   no2       1517 non-null   object
 8   max       1517 non-null   object
 9   critical  1517 non-null   object
 10  categori  1517 non-null   object
dtypes: object(11)
memory usage: 142.2+ KB

In [ ]:
# Konversi tipe data polutan str menjadi int

df_2021_new = df_2021_new.astype({'pm10': int, 'pm25': int, 'so2': int, 'co': int, 'o3': int, 'no2': int, 'max': int})

df_2021_new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1517 entries, 0 to 1824
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   tanggal   1517 non-null   object
 1   stasiun   1517 non-null   object
 2   pm10      1517 non-null   int64
 3   pm25      1517 non-null   int64
 4   so2       1517 non-null   int64
 5   co        1517 non-null   int64
 6   o3        1517 non-null   int64
 7   no2       1517 non-null   int64
 8   max       1517 non-null   int64
 9   critical  1517 non-null   object
 10  categori  1517 non-null   object
dtypes: int64(7), object(4)
memory usage: 142.2+ KB

In [ ]:
# Export file data ISPU 2021 bersih

df_2021_new.to_excel('ISPU 2021 Hasil Cleaning.xlsx', index=False)

In [ ]:
df_2021_new.describe()

,pm10,pm25,so2,co,o3,no2,max
count,1517.000000,1517.000000,1517.000000,1517.000000,1517.000000,1517.000000,1517.000000
mean,52.874753,78.238629,35.720501,11.914305,31.338167,20.423204,79.238629
std,14.705020,23.178350,12.627751,4.779081,14.843322,9.458014,22.310143
min,15.000000,13.000000,2.000000,2.000000,8.000000,3.000000,20.000000
25%,45.000000,63.000000,26.000000,9.000000,21.000000,14.000000,64.000000
50%,54.000000,78.000000,36.000000,11.000000,28.000000,19.000000,79.000000
75%,62.000000,92.000000,45.000000,14.000000,38.000000,26.000000,93.000000
max,179.000000,174.000000,82.000000,43.000000,151.000000,65.000000,179.000000